/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentFunFactsRouteImport } from './routes/student/fun-facts'
import { Route as StudentListeningRouteImport } from './routes/student/listening'
import { Route as TutorIndexRouteImport } from './routes/tutor/index'
import { Route as TutorOnboardingRouteImport } from './routes/tutor/onboarding'
import { Route as TutorResearchRouteImport } from './routes/tutor/research'
import { Route as TutorSummariserRouteImport } from './routes/tutor/summariser'
import { Route as TutorStudentsStudentIdRouteImport } from './routes/tutor/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentFunFactsRoute = StudentFunFactsRouteImport.update({
  id: '/student/fun-facts',
  path: '/student/fun-facts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentListeningRoute = StudentListeningRouteImport.update({
  id: '/student/listening',
  path: '/student/listening',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorIndexRoute = TutorIndexRouteImport.update({
  id: '/tutor/',
  path: '/tutor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorOnboardingRoute = TutorOnboardingRouteImport.update({
  id: '/tutor/onboarding',
  path: '/tutor/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorResearchRoute = TutorResearchRouteImport.update({
  id: '/tutor/research',
  path: '/tutor/research',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorSummariserRoute = TutorSummariserRouteImport.update({
  id: '/tutor/summariser',
  path: '/tutor/summariser',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorStudentsStudentIdRoute = TutorStudentsStudentIdRouteImport.update({
  id: '/tutor/students/$studentId',
  path: '/tutor/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student/fun-facts': typeof StudentFunFactsRoute
  '/student/listening': typeof StudentListeningRoute
  '/tutor/onboarding': typeof TutorOnboardingRoute
  '/tutor/research': typeof TutorResearchRoute
  '/tutor/summariser': typeof TutorSummariserRoute
  '/student/': typeof StudentIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/students/$studentId': typeof TutorStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/student/fun-facts': typeof StudentFunFactsRoute
  '/student/listening': typeof StudentListeningRoute
  '/tutor/onboarding': typeof TutorOnboardingRoute
  '/tutor/research': typeof TutorResearchRoute
  '/tutor/summariser': typeof TutorSummariserRoute
  '/student': typeof StudentIndexRoute
  '/tutor': typeof TutorIndexRoute
  '/tutor/students/$studentId': typeof TutorStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student/fun-facts': typeof StudentFunFactsRoute
  '/student/listening': typeof StudentListeningRoute
  '/tutor/onboarding': typeof TutorOnboardingRoute
  '/tutor/research': typeof TutorResearchRoute
  '/tutor/summariser': typeof TutorSummariserRoute
  '/student/': typeof StudentIndexRoute
  '/tutor/': typeof TutorIndexRoute
  '/tutor/students/$studentId': typeof TutorStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student/fun-facts'
    | '/student/listening'
    | '/tutor/onboarding'
    | '/tutor/research'
    | '/tutor/summariser'
    | '/student/'
    | '/tutor/'
    | '/tutor/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/student/fun-facts'
    | '/student/listening'
    | '/tutor/onboarding'
    | '/tutor/research'
    | '/tutor/summariser'
    | '/student'
    | '/tutor'
    | '/tutor/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/student/fun-facts'
    | '/student/listening'
    | '/tutor/onboarding'
    | '/tutor/research'
    | '/tutor/summariser'
    | '/student/'
    | '/tutor/'
    | '/tutor/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentFunFactsRoute: typeof StudentFunFactsRoute
  StudentListeningRoute: typeof StudentListeningRoute
  TutorOnboardingRoute: typeof TutorOnboardingRoute
  TutorResearchRoute: typeof TutorResearchRoute
  TutorSummariserRoute: typeof TutorSummariserRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TutorIndexRoute: typeof TutorIndexRoute
  TutorStudentsStudentIdRoute: typeof TutorStudentsStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/fun-facts': {
      id: '/student/fun-facts'
      path: '/student/fun-facts'
      fullPath: '/student/fun-facts'
      preLoaderRoute: typeof StudentFunFactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/listening': {
      id: '/student/listening'
      path: '/student/listening'
      fullPath: '/student/listening'
      preLoaderRoute: typeof StudentListeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/': {
      id: '/tutor/'
      path: '/tutor'
      fullPath: '/tutor/'
      preLoaderRoute: typeof TutorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/onboarding': {
      id: '/tutor/onboarding'
      path: '/tutor/onboarding'
      fullPath: '/tutor/onboarding'
      preLoaderRoute: typeof TutorOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/research': {
      id: '/tutor/research'
      path: '/tutor/research'
      fullPath: '/tutor/research'
      preLoaderRoute: typeof TutorResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/summariser': {
      id: '/tutor/summariser'
      path: '/tutor/summariser'
      fullPath: '/tutor/summariser'
      preLoaderRoute: typeof TutorSummariserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/students/$studentId': {
      id: '/tutor/students/$studentId'
      path: '/tutor/students/$studentId'
      fullPath: '/tutor/students/$studentId'
      preLoaderRoute: typeof TutorStudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentFunFactsRoute: StudentFunFactsRoute,
  StudentListeningRoute: StudentListeningRoute,
  TutorOnboardingRoute: TutorOnboardingRoute,
  TutorResearchRoute: TutorResearchRoute,
  TutorSummariserRoute: TutorSummariserRoute,
  StudentIndexRoute: StudentIndexRoute,
  TutorIndexRoute: TutorIndexRoute,
  TutorStudentsStudentIdRoute: TutorStudentsStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
